# Variable
@baseUrl = http://localhost:3333

# Health Check
# @name healthCheck

GET {{baseUrl}}/health

###

# Get Rooms
# @name getRooms
GET {{baseUrl}}/rooms

###

# Create Room
# @name createRoom
POST {{baseUrl}}/rooms
Content-Type: application/json

{
  "name": "Sala de teste",
  "description": "Essa é uma sala de teste"
}

###

@roomId = {{createRoom.response.body.$.roomId}}

###

# Get Room Question
# @name getRoomQuestions
GET {{baseUrl}}/rooms/{{roomId}}/questions

###

# Create Question
# @name createQuestion
POST {{baseUrl}}/rooms/48e119de-3f49-4a1e-ab16-cf1a369d8092/questions
Content-Type: application/json

{
  "question": "O que é Vue.js e a sua diferença em relação ao Angular?"
}